// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iveqhodzxyrhxqzjppqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2ZXFob2R6eHlyaHhxempwcHFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NDg1NzgsImV4cCI6MjA2OTUyNDU3OH0.7qcX7wEDfEFL3u8ucN64nYIdTsE0oPy4wP14Gc6_V9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});